# 数值运算的lib：NumPy

In [2]:
import numpy as np
np.version.full_version

'2.1.3'

## 数组对象

In [4]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
a = a.reshape(4, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
# 构造更高维
a = a.reshape(2, 2, 5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [18]:
# 数组对象的相关属性
print(f"维度：{a.ndim}")
print(f"各维度的大小：{a.shape}")
print(f"全部元素个数：{a.size}")
print(f"元素类型：{a.dtype}")
print(f"元素占位字节数：{a.nbytes}") # 8位一个字节

维度：3
各维度的大小：(2, 2, 5)
全部元素个数：20
元素类型：int64
元素占位字节数：160


## 创建数组

In [19]:
raw = [0,1,2,3,4]
a = np.array(raw)
a

array([0, 1, 2, 3, 4])

In [20]:
raw = [[0,1,2,3,4], [5,6,7,8,9]]
b = np.array(raw)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 全零矩阵

In [21]:
d = (4, 5)
np.zeros(d)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 全1矩阵
默认生成的类型是浮点型，可以通过指定类型改为整型

In [23]:
d = (4, 5)
np.ones(d, dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 随机数数组

In [24]:
np.random.rand(5)

array([0.5873317 , 0.69730631, 0.22548451, 0.09484597, 0.40646396])

## 数组操作

简单的四则运算已经重载过了，全部的`+`，`-`，`*`，`/`运算都是基于全部的数组元素的

In [25]:
a = np.array([[1.0, 2], [2, 4]])
print("a:")
print(a)
b = np.array([[3.2, 1.5], [2.5, 4]])
print("b:")
print(b)
print("a+b:")
print(a+b)

a:
[[1. 2.]
 [2. 4.]]
b:
[[3.2 1.5]
 [2.5 4. ]]
a+b:
[[4.2 3.5]
 [4.5 8. ]]
